---
- name: Start Zookeeper
  become: true
  command: screen -dmS zookeeper bash -c 'sudo /opt/kafka_2.13-3.6.1/bin/zookeeper-server-start.sh "/opt/kafka_2.13-3.6.1/config/zookeeper.properties"; exec bash'
  when: "'Zookeeper' in group_names"

- name: Wait for 5 seconds
  pause:
    seconds: 5

- name: Start Brokers
  become: true
  command: screen -dmS broker bash -c 'sudo /opt/kafka_2.13-3.6.1/bin/kafka-server-start.sh "/opt/kafka_2.13-3.6.1/config/server.properties"; exec bash'
# create weather data topics
# - name: Create topics
#   command: /opt/kafka_2.13-3.6.1/bin/kafka-topics.sh --create --topic {{ item }} --bootstrap-server {{private_ip}}:9092 --partitions 2 --replication-factor 2
#   loop:
#     - weather_nashville
#     - weather_chicago
#     - weather_atlanta
#   when: "'VM2' in group_names"
