- name: Run VM2 consumer
  command: "{{consumer_dir}}/consumer_vm2.py"
  when: "'Zookeeper' in group_names"

- name: Run VM3 consumer
  command: "{{consumer_dir}}/consumer_vm3.py"
  when: "'VM3' in group_names"
