- name: Run VM2 consumer
  become: true
  command: screen -dmS vm2_consumer python3 consumer_vm2.py
  when: "'VM2' in group_names"

- name: Run VM2 consumer (repeat)
  become: true
  command: screen -dmS vm2_consumer01 python3 consumer_vm2.py
  when: "'VM2' in group_names"

- name: Run VM3 consumer
  become: true
  command: screen -dmS vm3_consumer python3 consumer_vm3.py
  when: "'VM3' in group_names"
