- name: Run VM2 consumer
  become: true
  command: screen -dmS vm2_consumer bash -c 'python3 "{{consumer_dir}}/consumer_vm2.py"; exec bash'
  when: "'Zookeeper' in group_names"

- name: Run VM3 consumer
  become: true
  command: screen -dmS vm3_consumer bash -c 'python3 "{{consumer_dir}}/consumer_vm3.py"; exec bash'
  when: "'VM3' in group_names"
