---
- name: Start Zookeeper
  command: screen -dmS zookeeper bash -c 'sudo /opt/kafka_2.13-3.6.1/bin/zookeeper-server-start.sh "/opt/kafka_2.13-3.6.1/config/zookeeper.properties"; exec bash'
  when: "'Zookeeper' in group_names"
  become: yes

- name: Start Brokers
  command: screen -dmS broker bash -c 'sudo /opt/kafka_2.13-3.6.1/bin/kafka-server-start.sh "/opt/kafka_2.13-3.6.1/config/server.properties"; exec bash'
  when: "'MyAWSVMs' in group_names"
  become: yes
