apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: cloudgroup10
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
      volumes:
        - name: couchdb-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
spec:
  selector:
    app: couchdb
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30598
  type: NodePort