- name: Run kubeadm init
  command: sudo kubeadm init --pod-network-cidr=10.244.0.0/16

- name: Remove existing .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: absent
  ignore_errors: yes

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy admin.conf to user's .kube directory
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Apply the Flannel CNI
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- name: Restrart containerd
  shell: sudo systemctl restart containerd
