# - name: "Set cdn configuration for kubeadmin"
#   become: yes
#   lineinfile:
#     path: /var/lib/kubelet/kubeadm-flags.env
#     insertafter: EOF
#     line: "KUBELET_KUBEADM_ARGS=--resolv-conf=/run/systemd/resolve/resolv.conf"
# - name: restart Kubelet
#   become: yes
#   shell: sudo systemctl restart kubelet
- name: "Reset kubeadmin"
  expect:
    command: "sudo kubeadm reset"
    responses:
      'Are you sure you want to proceed\? \[y/N\]:': "y"
  ignore_errors: yes

- name: "Remove kubeadmin files"
  shell: |
    rm -fr ~/.kube
    sudo rm -fr /etc/cni/net.d
  ignore_errors: yes
