- name: Copy zookeeper manifest file
  copy:
    src: ../k8s/zookeeper/zookeeper.yaml
    dest: /tmp/zookeeper.yaml

- name: Apply zookeeper
  shell: kubectl apply -f /tmp/zookeeper.yaml

- name: Sleep for 10 seconds
  become: true
  shell: sleep 10

- name: Copy broker manifest file
  copy:
    src: ../k8s/broker/broker.yml
    dest: /tmp/broker.yml

- name: Apply broker
  shell: kubectl apply -f /tmp/broker.yml

- name: Copy couchdb manifest file
  copy:
    src: ../k8s/couchDB/couchdb.yml
    dest: /tmp/couchdb.yml

- name: Apply couchdb
  shell: kubectl apply -f /tmp/couchdb.yml

- name: Copy consumer_vm2 manifest file
  copy:
    src: ../k8s/consumers/consumer_vm2.yaml
    dest: /tmp/consumer_vm2.yaml

- name: Apply consumer1
  shell: kubectl apply -f /tmp/consumer_vm2.yaml

- name: Copy consumer_vm3 manifest file
  copy:
    src: ../k8s/consumers/consumer_vm3.yaml
    dest: /tmp/consumer_vm3.yaml

- name: Apply consumer2
  shell: kubectl apply -f /tmp/consumer_vm3.yaml
