- name: Run kubeadm init
  command: sudo kubeadm init --pod-network-cidr=10.244.0.0/16
  register: init_output

- name: Print init output
  debug:
    var: init_output.stdout

- name: Create .kube directory
  shell: "mkdir -p $HOME/.kube"

- name: Copy admin.conf to .kube directory
  become: true
  shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: Change ownership of .kube/config
  become: true
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Apply the Flannel CNI
  become: true
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Generate join command
  become: true
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: true
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
